---
- name: Get OS release
  ansible.builtin.debug:
    var: ansible_distribution_release

- name: Upgrade cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  tags: update_packages

## TIME 
- name: Enable timesyncd service
  ansible.builtin.systemd:
    enabled: true
    name: systemd-timesyncd
    state: started

- name: Set timezone
  community.general.timezone:
    name: Etc/UTC
  notify: Restart cron.service
# END TIME

- name: Install Figlet and Toilet
  shell: |
    if ! command -v figlet &> /dev/null || ! command -v toilet &> /dev/null; then
    echo -e "\033[0;33mFiglet or Toilet not found, installing..."
    sudo apt-get update && sudo apt-get install -y figlet toilet
    fi

- name: Generate MOTD news configuration file
  ansible.builtin.template:
    dest: /etc/default/motd-news
    group: root
    mode: "0644"
    owner: root
    src: motd-news.j2
  become: true

- name: Disable MOTD news update service
  ansible.builtin.systemd:
    enabled: false
    name: motd-news.timer
    state: stopped

- name: Remove unwanted MOTD configuration files
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  become: true
  loop:
    - 00-header
    - 10-help-text
    - 50-landscape-sysinfo
    - 50-motd-news
    - 88-esm-announce

- name: Generate custom MOTD
  ansible.builtin.template:
    dest: /etc/motd
    group: root
    mode: "0644"
    owner: root
    src: motd.j2
  become: true
  tags: update_hostname
  